/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 forest.gltf --transform 
Files: forest.gltf [658.14KB] > C:\Users\assta\OneDrive\Desktop\WanRakshak\forest-transformed.glb [454.26KB] (31%)
Author: Edgar_koh (https://sketchfab.com/edgar_koh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/camping-buscraft-ambience-7b65e4df95c3492fbf4e0641e3b472c1
Title: camping buscraft ambience
*/
import React, { useRef,useEffect,useState } from 'react';
import { extend,useFrame} from '@react-three/fiber';
import { TextGeometry } from 'three/examples/jsm/geometries/TextGeometry';
import { FontLoader } from 'three/examples/jsm/loaders/FontLoader';
import fontJson from './helvetiker_regular.typeface.json';
import { useGLTF, useAnimations,Html } from '@react-three/drei'
import {useNavigate} from 'react-router-dom';

export function Forest_transformed(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/forest-transformed.glb')
  const { actions } = useAnimations(animations, group)
  const forestRef = useRef();
  const [hovered, setHovered] = useState(false);
  const[hovered1,setHovered1] = useState(false);
  const[hovered2,setHovered2] =useState(false);
  const font = new FontLoader().parse(fontJson);

  useEffect(() => {
    const handleScroll = () => {
      if (forestRef.current) {
        forestRef.current.rotation.y += window.scrollY * 0.001; 
      }
    };
    window.addEventListener('scroll', handleScroll);

    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, []);
  const mesh = nodes.pPlatonic7_lambert7_0;


  return (
    <mesh ref={forestRef} position={[0, 0, 0]}>
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode">
          <group name="pPlane184" position={[1.61, -0.155, 1.723]} rotation={[-0.659, -0.451, -1.899]} scale={[0.156, 0.202, 0.101]}>
            <mesh name="pPlane184_lambert6_0" geometry={nodes.pPlane184_lambert6_0.geometry} material={materials.lambert6} />
          </group>
          <group name="pPlane185" position={[-1.985, 0.082, 3.846]} rotation={[-0.659, -0.451, -1.899]} scale={[0.156, 0.202, 0.101]}>
            <mesh name="pPlane185_lambert6_0" geometry={nodes.pPlane185_lambert6_0.geometry} material={materials.lambert6} />
          </group>
          <group name="pPlane186" position={[0.394, 3.924, 1.45]} rotation={[-0.659, -0.451, -1.899]} scale={[0.156, 0.202, 0.101]}>
            <mesh name="pPlane186_lambert6_0" geometry={nodes.pPlane186_lambert6_0.geometry} material={materials.lambert6} />
          </group>
          <group name="pPlane187" position={[-2.961, -0.993, 2.443]} rotation={[-0.659, -0.451, -1.899]} scale={[0.156, 0.202, 0.101]}>
            <mesh name="pPlane187_lambert6_0" geometry={nodes.pPlane187_lambert6_0.geometry} material={materials.lambert6} />
          </group>
          <group name="pPlane188" position={[1.911, 8.051, -2.183]} rotation={[-0.659, -0.451, -1.899]} scale={[0.156, 0.202, 0.101]}>
            <mesh name="pPlane188_lambert6_0" geometry={nodes.pPlane188_lambert6_0.geometry} material={materials.lambert6} />
          </group>
          <group name="pPlane189" position={[0.283, 7.103, 0.959]} rotation={[-0.659, -0.451, -1.899]} scale={[0.156, 0.202, 0.101]}>
            <mesh name="pPlane189_lambert6_0" geometry={nodes.pPlane189_lambert6_0.geometry} material={materials.lambert6} />
          </group>
          <group name="pPlane190" position={[-1.001, 0.21, 2.13]} rotation={[-0.659, -0.451, -1.899]} scale={[0.156, 0.202, 0.101]}>
            <mesh name="pPlane190_lambert6_0" geometry={nodes.pPlane190_lambert6_0.geometry} material={materials.lambert6} />
          </group>
          <group name="pPlane191" position={[-2.848, 4.306, 1.896]} rotation={[-0.659, -0.451, -1.899]} scale={[0.156, 0.202, 0.101]}>
            <mesh name="pPlane191_lambert6_0" geometry={nodes.pPlane191_lambert6_0.geometry} material={materials.lambert6} />
          </group>
          <group name="pPlane192" position={[2.035, 6.448, -1.815]} rotation={[-0.659, -0.451, -1.899]} scale={[0.156, 0.202, 0.101]}>
            <mesh name="pPlane192_lambert6_0" geometry={nodes.pPlane192_lambert6_0.geometry} material={materials.lambert6} />
          </group>
          <group name="pPlane193" position={[-1.571, 2.198, 1.267]} rotation={[-0.659, -0.451, -1.899]} scale={[0.156, 0.202, 0.101]}>
            <mesh name="pPlane193_lambert6_0" geometry={nodes.pPlane193_lambert6_0.geometry} material={materials.lambert6} />
          </group>
          <group name="pPlane194" position={[2.823, 4.467, 0.146]} rotation={[-0.659, -0.451, -1.899]} scale={[0.156, 0.202, 0.101]}>
            <mesh name="pPlane194_lambert6_0" geometry={nodes.pPlane194_lambert6_0.geometry} material={materials.lambert6} />
          </group>
          <group name="pPlane195" position={[0.046, 0.524, 2.345]} rotation={[-0.659, -0.451, -1.899]} scale={[0.156, 0.202, 0.101]}>
            <mesh name="pPlane195_lambert6_0" geometry={nodes.pPlane195_lambert6_0.geometry} material={materials.lambert6} />
          </group>
          <group name="pPlane196" position={[2.069, -0.623, 0.721]} rotation={[-0.659, -0.451, -1.899]} scale={[0.156, 0.202, 0.101]}>
            <mesh name="pPlane196_lambert6_0" geometry={nodes.pPlane196_lambert6_0.geometry} material={materials.lambert6} />
          </group>
        </group>
        <mesh name="pDisc1_lambert3_0" geometry={nodes.pDisc1_lambert3_0.geometry} material={materials.lambert3} position={[0, -0.064, 0]} scale={14.985} />
        <mesh name="pCylinder29_lambert5_0" geometry={nodes.pCylinder29_lambert5_0.geometry}onPointerOver={()=>setHovered1(true)} onPointerOut={()=>setHovered1(false)} onClick={()=>window.location.href='/Map'} material={materials.lambert5} position={[0.031, 1.5, 0.102]} />
        <mesh name="pCube4_lambert8_0" geometry={nodes.pCube4_lambert8_0.geometry} material={materials.lambert8} position={[2.807, 0.289, 1.726]} />
        <mesh name="polySurface91_lambert6_0" geometry={nodes.polySurface91_lambert6_0.geometry} material={materials.lambert6} position={[0, -0.045, 0]} />
        <mesh name="pPlatonic7_lambert7_0" geometry={nodes.pPlatonic7_lambert7_0.geometry} onPointerOver={()=>setHovered1(true)} onPointerOut={()=>setHovered1(false)} onClick={()=>window.location.href='/Educationhub'} material={materials.lambert7} position={[-6.512, -0.072, 3.127]} rotation={[-0.077, 1.311, 0.379]} scale={[0.261, 0.146, 0.235]} />
        <mesh name="fire3polySurface162_fire3lambert2_0" geometry={nodes.fire3polySurface162_fire3lambert2_0.geometry}material={materials.fire3lambert2}/>
        <mesh name="0" geometry={nodes['0'].geometry} onPointerOver={()=>setHovered(true)} onPointerOut={()=>setHovered(false)} onClick={()=>window.location.href='/3D'} material={hovered? materials.lambert9:'orange'} morphTargetDictionary={nodes['0'].morphTargetDictionary} morphTargetInfluences={nodes['0'].morphTargetInfluences} position={[2.825, 0.408, 1.729]} scale={0.286} />
        {font && <Tag position={[1.1, 1.0, 1.0]} font={font} text="ClickIn White_Box to Fire Time-Travel" />}
        {font && <Tag position={[-3.1, 3.4, -1.0]} rotation={[0, Math.PI, 0]} font={font} text="GetIn the Tent to dive in the world of Forest lovers" />}
        {font && <Tag position={[3.1, 2.4, 1.0]} rotation={[0, Math.PI, 0]} font={font} text="Look In the Bag for Plant Book" />}
      </group>
    </group>
    </mesh>
  )
}
function Tag({ position, text, font }) {
    return (
      <mesh position={position}>
      <textGeometry args={[text, { font, size: 0.2, height: 0.01 }]} />
      <meshStandardMaterial color="white" transparent={true} opacity={1} />
    </mesh>
    );
  }
useGLTF.preload('/forest-transformed.glb')
