/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/CartComp.glb -o ./src/models/Cart1.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function CarryCart(props) {
  const { nodes, materials } = useGLTF('/CartComp.glb')
  return (
    <group {...props} dispose={null}>
      <RigidBody type='fixed'>
      <mesh geometry={nodes.Cube060.geometry} material={materials.Glass} />
      <mesh geometry={nodes.Cube060_1.geometry} material={materials.Traders_cart_mat} />
      </RigidBody>
    </group>
  )
}

useGLTF.preload('/CartComp.glb')
