/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/HorseCartComp.glb -o ./src/models/Cart.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function Cart(props) {
  const { nodes, materials } = useGLTF('/HorseCartComp.glb')
  return (
    <group {...props} dispose={null}>
      <RigidBody type='fixed'>
      <mesh geometry={nodes.Barrel_body_Wood_0.geometry} material={materials.Wood} position={[1.072, 11.404, -1.109]} rotation={[-3.109, 0, 0]} scale={3.5} />
      <mesh geometry={nodes.Reins_Wood2_0.geometry} material={materials.Wood2} position={[24.186, 10.08, 0]} rotation={[-Math.PI / 2, 0.321, -0.015]} scale={[6, 7, 3]} />
      <mesh geometry={nodes.Wheel_LF_Metal_0.geometry} material={materials.Metal} position={[4.909, 3.367, -5.329]} rotation={[0, 0, 2.749]} scale={[3.5, 3.5, 5]} />
      <mesh geometry={nodes.Object_2.geometry} material={materials.defaultMat} position={[19.166, 0.042, 0]} rotation={[-Math.PI / 2, 0, 1.577]} scale={0.7} />
      </RigidBody>
    </group>
  )
}

useGLTF.preload('/HorseCartComp.glb')
