/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/Hindu_templeComp.glb -o src/models/HinduTempleModel.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function Hindu(props) {
  const { nodes, materials } = useGLTF('/Hindu_templeComp.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[4,0,9]}>
      <mesh geometry={nodes.Object_49.geometry} material={materials.bell} position={[0.219, 2.212, 9.277]} />
      <mesh geometry={nodes.Object_39.geometry} material={materials.pillar_bell} position={[0.219, 2.212, 9.277]} scale={[0.399, 2.174, 0.399]} />
      <mesh geometry={nodes.Object_41.geometry} material={materials.BASE_PILLAR} position={[0.219, 2.818, 9.277]} scale={[0.399, 2.174, 0.399]} />
      <mesh geometry={nodes.Object_43.geometry} material={materials.base_illar2} position={[0.219, 2.818, 9.277]} scale={[0.399, 2.174, 0.399]} />
      <mesh geometry={nodes.Object_45.geometry} material={materials.big_tomb} position={[0.219, 8.037, 9.277]} scale={[1.417, 1, 0.497]} />
      <mesh geometry={nodes.Object_47.geometry} material={materials.small_tomb} position={[-1.716, 7.49, 9.277]} scale={0.453} />
      <mesh geometry={nodes.Object_55.geometry} material={materials.ball} position={[0.219, 2.389, 9.277]} scale={0.164} />
      <instancedMesh args={[nodes.Object_25_1.geometry, materials.PaletteMaterial001, 4]} instanceMatrix={nodes.Object_25_1.instanceMatrix} />
      </group>
      <group scale={[3.5,3.5,3.5]} position={[4,-4.3,-10]}>
      <RigidBody type='fixed' colliders='cuboid'>
      <mesh geometry={nodes.Object_8.geometry} material={materials.linga} position={[-.3, 1.4, -0.17]} scale={0.236} /> 
      </RigidBody>
      <mesh geometry={nodes.Object_15.geometry} material={materials.temple_ground} position={[-0.338, 3.674, 0.094]} scale={[1.2,2.2,1.2]}/>
      <mesh geometry={nodes.Object_12.geometry} material={materials.temple_outter} position={[-.33, 11.9, 0]} scale={[.8, 2.6, 1 ]} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.mid_fllor} position={[0, 5.8, 0]} scale={[4,5,4]} />
      <RigidBody type='fixed' colliders='trimesh'>
      <mesh geometry={nodes.Object_32.geometry} material={materials.pillar} position={[0, 2.9, 0]} scale={[.2,.2,.2]} />
      </RigidBody>
      </group>
      {/* <RigidBody type=/'fixed' colliders='cuboid'> */}
      {/* <mesh geometry={nodes.Object_25.geometry} material={materials.statue} position={[4 , .904, -9]} scale={[2, .03, 2]} /> */}
      {/* </RigidBody> */}
      {/* <mesh geometry={nodes.Object_27.geometry} material={materials.floor} position={[0, 1.898, 0]} scale={3.481} /> */}
      {/* <mesh geometry={nodes.Object_34.geometry} material={materials['small_tomb.001']} position={[1.579, 5.978, 1.749]} rotation={[0, -Math.PI / 6, 0]} scale={0.04} /> */}
      {/* <instancedMesh args={[nodes.Object_1.geometry, materials.bigtomb, 2]} instanceMatrix={nodes.Object_1.instanceMatrix} /> */}
      {/* <instancedMesh args={[nodes.Object_7.geometry, materials.temple_top_design, 2]} instanceMatrix={nodes.Object_7.instanceMatrix} /> */}
      {/* <instancedMesh args={[nodes.Object_9.geometry, materials.statue, 2]} instanceMatrix={nodes.Object_9.instanceMatrix} /> */}
    </group>
  )
}

useGLTF.preload('/Hindu_templeComp.glb')
