/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/HouseComp.glb -o ./src/models/Hut.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function Hut(props) {
  const { nodes, materials } = useGLTF('/HouseComp.glb')
  return (
    <group {...props} dispose={null}>
      <RigidBody type='fixed' colliders='trimesh'>
      <mesh geometry={nodes._gltfNode_0.geometry} material={materials['Material.015']} position={[-2.724, 4.24, 3.99]} rotation={[Math.PI, -1.305, Math.PI]} />
      <mesh geometry={nodes._gltfNode_4.geometry} material={nodes._gltfNode_4.material} position={[-2.724, 2.87, 3.99]} />
      <mesh geometry={nodes._gltfNode_26.geometry} material={materials['Material.003']} position={[4.626, 0, -3.321]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes._gltfNode_58.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes._gltfNode_60.geometry} material={materials['Material.016']} position={[-7.507, -0.471, -0.399]} />
      <instancedMesh args={[nodes.Mesh_8.geometry, materials['Material.004'], 5]} instanceMatrix={nodes.Mesh_8.instanceMatrix} />
      <instancedMesh args={[nodes.Mesh_14.geometry, nodes.Mesh_14.material, 9]} instanceMatrix={nodes.Mesh_14.instanceMatrix} />
      <instancedMesh args={[nodes.Mesh_23.geometry, nodes.Mesh_23.material, 6]} instanceMatrix={nodes.Mesh_23.instanceMatrix} />
      <instancedMesh args={[nodes.Mesh_32.geometry, materials['Material.004'], 6]} instanceMatrix={nodes.Mesh_32.instanceMatrix} />
      <instancedMesh args={[nodes.Mesh_41.geometry, materials['Material.004'], 2]} instanceMatrix={nodes.Mesh_41.instanceMatrix} />
      <instancedMesh args={[nodes.Mesh_47.geometry, materials['Material.004'], 6]} instanceMatrix={nodes.Mesh_47.instanceMatrix} />
      <instancedMesh args={[nodes.Mesh_56.geometry, materials['Material.004'], 2]} instanceMatrix={nodes.Mesh_56.instanceMatrix} />
      <instancedMesh args={[nodes.Mesh_64.geometry, materials['Material.004'], 6]} instanceMatrix={nodes.Mesh_64.instanceMatrix} />
      <instancedMesh args={[nodes.Mesh_69.geometry, materials['Material.004'], 6]} instanceMatrix={nodes.Mesh_69.instanceMatrix} />
      <instancedMesh args={[nodes.Mesh_79.geometry, materials['Material.018'], 6]} instanceMatrix={nodes.Mesh_79.instanceMatrix} />
      <instancedMesh args={[nodes.Mesh_84.geometry, materials['Material.018'], 6]} instanceMatrix={nodes.Mesh_84.instanceMatrix} />
      <instancedMesh args={[nodes.Mesh_87.geometry, materials['Material.004'], 3]} instanceMatrix={nodes.Mesh_87.instanceMatrix} />
      </RigidBody>
    </group>
  )
}

useGLTF.preload('/HouseComp.glb')
