/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/peakockComp.glb -o ./src/models/Peackock.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Peackock(props) {
  const { nodes, materials } = useGLTF('/peakockComp.glb')

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['mesh130dat_body-feather05001_0'].geometry} material={materials['body-feather05.001']} position={[7.111, 16.59, 14.701]} rotation={[-1.782, 1.438, 0]} scale={17.38} />
      <mesh geometry={nodes.mesh202dat_body_0.geometry} material={materials.body} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['mesh203dat_body-feather02007_0'].geometry} material={materials['body-feather02.007']} position={[6.23, 13.079, 9.616]} rotation={[-2.249, 1.087, 0.035]} scale={37.338} />
      <mesh geometry={nodes['mesh205dat_body-feather01020_0'].geometry} material={materials['body-feather01.020']} position={[5.612, 27.019, 32.643]} rotation={[Math.PI / 2, 0.093, 0]} scale={39.266} />
      <mesh geometry={nodes.mesh252dat_crest02017_0.geometry} material={materials['crest02.017']} position={[0, 47.295, 29.292]} rotation={[-2.979, 0, 0]} scale={20.75} />
      <mesh geometry={nodes.mesh255dat_back_0.geometry} material={materials.back} position={[0.28, 29.913, 4.989]} rotation={[-0.23, 0, 0]} />
      <instancedMesh args={[nodes['mesh129dat_body-feather05001_0'].geometry, materials['body-feather05.001'], 6]} instanceMatrix={nodes['mesh129dat_body-feather05001_0'].instanceMatrix} />
      <instancedMesh args={[nodes['mesh160dat_body-feather05001_0'].geometry, materials['body-feather05.001'], 2]} instanceMatrix={nodes['mesh160dat_body-feather05001_0'].instanceMatrix} />
      <instancedMesh args={[nodes['mesh204dat_body-feather01020_0'].geometry, materials['body-feather01.020'], 5]} instanceMatrix={nodes['mesh204dat_body-feather01020_0'].instanceMatrix} />
      <instancedMesh args={[nodes['mesh206dat_body-feather01020_0'].geometry, materials['body-feather01.020'], 3]} instanceMatrix={nodes['mesh206dat_body-feather01020_0'].instanceMatrix} />
      <instancedMesh args={[nodes['mesh207dat_body-feather01020_0'].geometry, materials['body-feather01.020'], 2]} instanceMatrix={nodes['mesh207dat_body-feather01020_0'].instanceMatrix} />
      <instancedMesh args={[nodes['mesh210dat_body-feather01020_0'].geometry, materials['body-feather01.020'], 2]} instanceMatrix={nodes['mesh210dat_body-feather01020_0'].instanceMatrix} />
      <instancedMesh args={[nodes['mesh221dat_body-feather01020_0'].geometry, materials['body-feather01.020'], 2]} instanceMatrix={nodes['mesh221dat_body-feather01020_0'].instanceMatrix} />
      <instancedMesh args={[nodes['mesh222dat_body-feather02007_0'].geometry, materials['body-feather02.007'], 2]} instanceMatrix={nodes['mesh222dat_body-feather02007_0'].instanceMatrix} />
      <instancedMesh args={[nodes['mesh223dat_body-feather01020_0'].geometry, materials['body-feather01.020'], 2]} instanceMatrix={nodes['mesh223dat_body-feather01020_0'].instanceMatrix} />
      <instancedMesh args={[nodes['mesh229dat_body-feather01020_0'].geometry, materials['body-feather01.020'], 2]} instanceMatrix={nodes['mesh229dat_body-feather01020_0'].instanceMatrix} />
      <instancedMesh args={[nodes['mesh230dat_body-feather01020_0'].geometry, materials['body-feather01.020'], 2]} instanceMatrix={nodes['mesh230dat_body-feather01020_0'].instanceMatrix} />
      <instancedMesh args={[nodes['mesh232dat_body-feather01020_0'].geometry, materials['body-feather01.020'], 2]} instanceMatrix={nodes['mesh232dat_body-feather01020_0'].instanceMatrix} />
      <instancedMesh args={[nodes.polySurface1_aiStandardSurface1_0.geometry, materials.aiStandardSurface1, 14]} instanceMatrix={nodes.polySurface1_aiStandardSurface1_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface4002_aiStandardSurface2_0.geometry, materials.aiStandardSurface2, 66]} instanceMatrix={nodes.polySurface4002_aiStandardSurface2_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface4004_aiStandardSurface1_0.geometry, materials.aiStandardSurface1, 50]} instanceMatrix={nodes.polySurface4004_aiStandardSurface1_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface4004_aiStandardSurface2_0.geometry, materials.aiStandardSurface2, 50]} instanceMatrix={nodes.polySurface4004_aiStandardSurface2_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface4005_aiStandardSurface1_0.geometry, materials.aiStandardSurface1, 86]} instanceMatrix={nodes.polySurface4005_aiStandardSurface1_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface4005_aiStandardSurface2_0.geometry, materials.aiStandardSurface2, 86]} instanceMatrix={nodes.polySurface4005_aiStandardSurface2_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface5_aiStandardSurface2_0.geometry, materials.aiStandardSurface2, 11]} instanceMatrix={nodes.polySurface5_aiStandardSurface2_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface5_aiStandardSurface3_0.geometry, materials.aiStandardSurface3, 11]} instanceMatrix={nodes.polySurface5_aiStandardSurface3_0.instanceMatrix} />
      <instancedMesh args={[nodes.Sphere_Eyeball__Pixel_Eyeball_0.geometry, materials['body-feather05.001'], 2]} instanceMatrix={nodes.Sphere_Eyeball__Pixel_Eyeball_0.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/peakockComp.glb')
