/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/Tree2Opt.glb -o src/models/Tree2.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function Tree2Model(props) {
  const { nodes, materials } = useGLTF('/Tree2Opt.glb')
  return (
    <group {...props} dispose={null}>
      {/* <RigidBody type='fixed' colliders='hull'> */}
      <mesh geometry={nodes.tree.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.leaves.geometry} material={materials['Material.001']} />
      {/* </RigidBody> */}
    </group>
  )
}

useGLTF.preload('/Tree2Opt.glb')
