/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/Tree3Comp.glb -o src/models/Tree3.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function Tree3Model(props) {
  const { nodes, materials } = useGLTF('/Tree3Comp.glb')
  return (
    <group {...props} dispose={null}>
      {/* <RigidBody type='fixed' colliders='hull'> */}
      <mesh geometry={nodes.TreeBirch.geometry} material={materials.PaletteMaterial001} />
      {/* </RigidBody> */}
    </group>
  )
}

useGLTF.preload('/Tree3Comp.glb')
