/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/Tree1Comp.glb -o src/models/Tree1.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { Tiger } from './Tiger'
import { RigidBody } from '@react-three/rapier'
export function Tree1Model(props) {
  const { nodes, materials } = useGLTF('/Tree1Comp.glb')
  return (
    <group {...props} dispose={null}>
      {/* <RigidBody type='fixed' colliders='hull'> */}
      <mesh geometry={nodes.jacaranda_tree_trunk.geometry} material={materials.jacaranda_tree_trunk} />
      <mesh geometry={nodes.jacaranda_tree_branches.geometry} material={materials.jacaranda_tree_branches} />
      <mesh geometry={nodes.jacaranda_tree_leaves.geometry} material={materials.jacaranda_tree_leaves} />
      {/* </RigidBody> */}
    </group>
  )
}

useGLTF.preload('/Tree1Comp.glb')
