/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/mountainsComp.glb -o ./src/Mountain.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function Mountain(props) {
  const { nodes, materials } = useGLTF('/mountainsComp.glb')
  return (
    <group {...props} dispose={null}>
      <RigidBody type='fixed'colliders='hull' >
      {/* <mesh geometry={nodes.Object_3.geometry} material={materials.base} position={[-114.939, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} /> */}
      <mesh geometry={nodes.Object_4.geometry} material={materials.cliff} position={[-114.939, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      </RigidBody>
      <mesh geometry={nodes.Object_5.geometry} material={materials.cloud} position={[-114.939, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/mountainsComp.glb')
